# Generated by Django 5.2.1 on 2025-06-20 18:55

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geophraphy',
            fields=[
                ('iso', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('flag', models.TextField()),
                ('capital', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('shape', models.TextField()),
                ('long', models.CharField(max_length=10)),
                ('lat', models.CharField(max_length=10)),
                ('population', models.IntegerField()),
                ('area', models.IntegerField()),
                ('continent', models.CharField(choices=[('AF', 'AFRIQUE'), ('NA', 'AMERIQUE DU NORD'), ('SA', 'AMERIQUE DU SUD'), ('AN', 'ANTARCTIQUE'), ('AS', 'ASIE'), ('EU', 'EUROPE')], default='EU')),
                ('langue', models.TextField(validators=[quiz.models.validate_langue])),
            ],
        ),
        migrations.CreateModel(
            name='Japanese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.TextField()),
                ('hiragana', models.TextField()),
                ('katakana', models.TextField()),
                ('kanji', models.TextField()),
                ('romaji', models.TextField()),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
