# Generated by Django 5.2.1 on 2025-06-05 17:10

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geophraphy',
            fields=[
                ('iso', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('flag', models.TextField()),
                ('capital', models.CharField(max_length=50)),
                ('shape', models.TextField()),
                ('long', models.CharField(max_length=10)),
                ('lat', models.CharField(max_length=10)),
                ('population', models.IntegerField()),
                ('continent', models.CharField(choices=[('AF', 'AFRIQUE'), ('NA', 'AMERIQUE DU NORD'), ('SA', 'AMERIQUE DU SUD'), ('AN', 'ANTARCTIQUE'), ('AS', 'ASIE'), ('EU', 'EUROPE')])),
                ('langue', models.TextField(validators=[quiz.models.validate_langue])),
            ],
        ),
    ]
