# Generated by Django 5.2.1 on 2025-06-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_geophraphy_lat_alter_geophraphy_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='japanese',
            old_name='hiragana',
            new_name='furigana',
        ),
        migrations.RemoveField(
            model_name='japanese',
            name='katakana',
        ),
    ]
