# Generated by Django 5.2.1 on 2025-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_hiragana_japanese_furigana_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='japanese',
            old_name='romaji',
            new_name='kunyomi',
        ),
        migrations.AddField(
            model_name='japanese',
            name='onyomi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='japanese',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
